/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.ArmedCharacter;
import model.SubType;
import model.WarriorType;
import model.WeaponType;
import model.builder.CharacterBuilder;
import model.factory.WeaponFactory;
import model.factory.WeaponFactoryMethod;
import model.prototype.PrototypeFactory;

/**
 *
 * @author Óscar Vega R
 */
public class TestFrame extends JFrame {
    
    private CharacterBuilder warriorBuilder;
    private WeaponFactoryMethod factoryWeapon;
    private ArmedCharacter warriorArmed;
    private JFileChooser fileChooser = new JFileChooser();

    /**
     * Creates new form TestFrame
     */
    public TestFrame() {
        warriorBuilder = new CharacterBuilder();
        factoryWeapon = new WeaponFactory();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF", "jpg", "gif");
        fileChooser.setFileFilter(filter);
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        weaponImage = new javax.swing.JLabel();
        principalImage = new javax.swing.JLabel();
        leftImage = new javax.swing.JLabel();
        rightImage = new javax.swing.JLabel();
        downImage = new javax.swing.JLabel();
        UpImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        type1 = new javax.swing.JComboBox<>();
        subType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        appearanceLevel = new javax.swing.JSlider();
        lblPrice = new javax.swing.JLabel();
        lblAppearanceLevel = new javax.swing.JLabel();
        price = new javax.swing.JSlider();
        fondo1 = new javax.swing.JPanel();
        lblLevel = new javax.swing.JLabel();
        level = new javax.swing.JSlider();
        lblSlots = new javax.swing.JLabel();
        slots = new javax.swing.JSlider();
        lblDamage = new javax.swing.JLabel();
        damage = new javax.swing.JSlider();
        lblLife = new javax.swing.JLabel();
        life = new javax.swing.JSlider();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        warriors = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Primer Proyecto");
        getContentPane().setLayout(new java.awt.BorderLayout());

        fondo.setLayout(null);
        getContentPane().add(fondo, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Creación de Personajes"));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(null);

        jButton3.setText("Clonar");
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 890, 370, 25);

        weaponImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weaponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/NONE.jpg"))); // NOI18N
        weaponImage.setToolTipText("Presione para agregar imagen");
        weaponImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));
        weaponImage.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(weaponImage);
        weaponImage.setBounds(130, 510, 150, 170);

        principalImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        principalImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/head128.png"))); // NOI18N
        principalImage.setToolTipText("Presione para agregar imagen");
        principalImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Principal"));
        principalImage.setPreferredSize(new java.awt.Dimension(150, 150));
        principalImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalImageMouseClicked(evt);
            }
        });
        jPanel1.add(principalImage);
        principalImage.setBounds(20, 40, 150, 170);

        leftImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/head64.png"))); // NOI18N
        leftImage.setToolTipText("Presione para agregar imagen");
        leftImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Izquierda"));
        leftImage.setPreferredSize(new java.awt.Dimension(100, 100));
        leftImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leftImageMouseClicked(evt);
            }
        });
        jPanel1.add(leftImage);
        leftImage.setBounds(290, 130, 100, 100);

        rightImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/head64.png"))); // NOI18N
        rightImage.setToolTipText("Presione para agregar imagen");
        rightImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Derecha"));
        rightImage.setPreferredSize(new java.awt.Dimension(100, 100));
        rightImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightImageMouseClicked(evt);
            }
        });
        jPanel1.add(rightImage);
        rightImage.setBounds(290, 30, 100, 100);

        downImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        downImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/head64.png"))); // NOI18N
        downImage.setToolTipText("Presione para agregar imagen");
        downImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Abajo"));
        downImage.setPreferredSize(new java.awt.Dimension(100, 100));
        downImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                downImageMouseClicked(evt);
            }
        });
        jPanel1.add(downImage);
        downImage.setBounds(180, 130, 100, 100);

        UpImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UpImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/head64.png"))); // NOI18N
        UpImage.setToolTipText("Presione para agregar imagen");
        UpImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Arriba"));
        UpImage.setPreferredSize(new java.awt.Dimension(100, 100));
        UpImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpImageMouseClicked(evt);
            }
        });
        jPanel1.add(UpImage);
        UpImage.setBounds(180, 30, 100, 100);

        jLabel2.setText("SubTipo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 240, 60, 16);

        Cantidad.setText("Cantidad de Guerreros:");
        jPanel1.add(Cantidad);
        Cantidad.setBounds(130, 820, 140, 16);

        type1.setModel(new DefaultComboBoxModel(WeaponType.values()));
        type1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type1ActionPerformed(evt);
            }
        });
        jPanel1.add(type1);
        type1.setBounds(130, 700, 150, 30);

        subType.setModel(new DefaultComboBoxModel(SubType.values()));
        jPanel1.add(subType);
        subType.setBounds(240, 260, 150, 30);

        jLabel1.setText("Tipo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 240, 40, 16);

        type.setModel(new DefaultComboBoxModel(WarriorType.values()));
        jPanel1.add(type);
        type.setBounds(20, 260, 150, 30);

        appearanceLevel.setValue(0);
        appearanceLevel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                appearanceLevelStateChanged(evt);
            }
        });
        jPanel1.add(appearanceLevel);
        appearanceLevel.setBounds(20, 420, 180, 26);

        lblPrice.setText("Precio: ");
        jPanel1.add(lblPrice);
        lblPrice.setBounds(210, 400, 180, 16);

        lblAppearanceLevel.setText("Nivel de Aparición: ");
        jPanel1.add(lblAppearanceLevel);
        lblAppearanceLevel.setBounds(20, 400, 170, 16);

        price.setValue(0);
        price.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceStateChanged(evt);
            }
        });
        jPanel1.add(price);
        price.setBounds(210, 420, 180, 26);

        fondo1.setLayout(null);
        jPanel1.add(fondo1);
        fondo1.setBounds(0, 50, 0, 0);

        lblLevel.setText("Nivel: ");
        jPanel1.add(lblLevel);
        lblLevel.setBounds(20, 350, 170, 16);

        level.setMaximum(3);
        level.setMinimum(1);
        level.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                levelStateChanged(evt);
            }
        });
        jPanel1.add(level);
        level.setBounds(20, 370, 180, 26);

        lblSlots.setText("Cantidad de Espacios: ");
        jPanel1.add(lblSlots);
        lblSlots.setBounds(210, 350, 180, 16);

        slots.setMaximum(8);
        slots.setMinimum(2);
        slots.setValue(0);
        slots.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slotsStateChanged(evt);
            }
        });
        jPanel1.add(slots);
        slots.setBounds(210, 370, 180, 26);

        lblDamage.setText("Cantidad de Golpes: ");
        jPanel1.add(lblDamage);
        lblDamage.setBounds(210, 300, 180, 16);

        damage.setValue(0);
        damage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                damageStateChanged(evt);
            }
        });
        jPanel1.add(damage);
        damage.setBounds(210, 320, 180, 26);

        lblLife.setText("Vida: ");
        jPanel1.add(lblLife);
        lblLife.setBounds(20, 300, 170, 16);

        life.setValue(0);
        life.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lifeStateChanged(evt);
            }
        });
        jPanel1.add(life);
        life.setBounds(20, 320, 180, 26);

        jButton2.setText("Agregar Arma");
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 750, 370, 25);

        jButton1.setText("Construir Personaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 460, 370, 25);
        jPanel1.add(warriors);
        warriors.setBounds(130, 840, 140, 30);

        jLabel4.setText("Tipo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 680, 40, 16);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lifeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lifeStateChanged
        // TODO add your handling code here:
        lblLife.setText("Vida: "+((JSlider)evt.getSource()).getValue());
    }//GEN-LAST:event_lifeStateChanged

    private void damageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_damageStateChanged
        // TODO add your handling code here:
        lblDamage.setText("Cantidad de Golpes: "+((JSlider)evt.getSource()).getValue());
    }//GEN-LAST:event_damageStateChanged

    private void levelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_levelStateChanged
        // TODO add your handling code here:
        lblLevel.setText("Nivel: "+((JSlider)evt.getSource()).getValue());
    }//GEN-LAST:event_levelStateChanged

    private void slotsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slotsStateChanged
        lblSlots.setText("Cantidad de Golpes: "+((JSlider)evt.getSource()).getValue());
    }//GEN-LAST:event_slotsStateChanged

    private void appearanceLevelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_appearanceLevelStateChanged
        // TODO add your handling code here:
        lblAppearanceLevel.setText("Nivel de Aparición: "+((JSlider)evt.getSource()).getValue());
    }//GEN-LAST:event_appearanceLevelStateChanged

    private void priceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceStateChanged
        lblPrice.setText("Precio: "+((JSlider)evt.getSource()).getValue());
    }//GEN-LAST:event_priceStateChanged

    private void principalImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalImageMouseClicked
        // TODO add your handling code here:
        int select = fileChooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
             String ruta = fileChooser.getSelectedFile().getAbsolutePath();
             warriorBuilder.addAppearances(ruta);
             ((JLabel)evt.getSource()).setIcon(new javax.swing.ImageIcon(ruta));
        }
    }//GEN-LAST:event_principalImageMouseClicked

    private void UpImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpImageMouseClicked
        // TODO add your handling code here:
        int select = fileChooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
             String ruta = fileChooser.getSelectedFile().getAbsolutePath();
             warriorBuilder.addAppearances(ruta);
             ((JLabel)evt.getSource()).setIcon(new javax.swing.ImageIcon(ruta));
        }
    }//GEN-LAST:event_UpImageMouseClicked

    private void rightImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightImageMouseClicked
        // TODO add your handling code here:
        int select = fileChooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
             String ruta = fileChooser.getSelectedFile().getAbsolutePath();
             warriorBuilder.addAppearances(ruta);
             ((JLabel)evt.getSource()).setIcon(new javax.swing.ImageIcon(ruta));
        }
    }//GEN-LAST:event_rightImageMouseClicked

    private void downImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_downImageMouseClicked
        // TODO add your handling code here:
        int select = fileChooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
             String ruta = fileChooser.getSelectedFile().getAbsolutePath();
             warriorBuilder.addAppearances(ruta);
             ((JLabel)evt.getSource()).setIcon(new javax.swing.ImageIcon(ruta));
        }
    }//GEN-LAST:event_downImageMouseClicked

    private void leftImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leftImageMouseClicked
        // TODO add your handling code here:
        int select = fileChooser.showOpenDialog(this);
        if (select == JFileChooser.APPROVE_OPTION) {
             String ruta = fileChooser.getSelectedFile().getAbsolutePath();
             warriorBuilder.addAppearances(ruta);
             ((JLabel)evt.getSource()).setIcon(new javax.swing.ImageIcon(ruta));
        }
    }//GEN-LAST:event_leftImageMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        warriorArmed = new ArmedCharacter(warriorBuilder.setNameType(((WarriorType)type.getSelectedItem()).getType()+level.getValue())
                .setNameSubType((SubType)subType.getSelectedItem())
                .setLife(life.getValue())
                .setDamage(damage.getValue())
                .setLevel(level.getValue())
                .setSlots(slots.getValue())
                .setAppearanceLevel(appearanceLevel.getValue())
                .setPrice(price.getValue())
                .build());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void type1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type1ActionPerformed
        // TODO add your handling code here:
        //"/view/images/
        //System.out.println("/view/images/"+((JComboBox)evt.getSource()).getSelectedItem().toString());
        weaponImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/"+((JComboBox)evt.getSource()).getSelectedItem().toString()+".jpg")));
        warriorArmed.addWeapon(((WeaponType)((JComboBox)evt.getSource()).getSelectedItem()).toString(), factoryWeapon.createWeapon((WeaponType)((JComboBox)evt.getSource()).getSelectedItem(), level.getValue()));
        PrototypeFactory.addPrototype(warriorArmed.getCharacter().getNameType(), warriorArmed);
    }//GEN-LAST:event_type1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel UpImage;
    private javax.swing.JSlider appearanceLevel;
    private javax.swing.JSlider damage;
    private javax.swing.JLabel downImage;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAppearanceLevel;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblLife;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSlots;
    private javax.swing.JLabel leftImage;
    private javax.swing.JSlider level;
    private javax.swing.JSlider life;
    private javax.swing.JSlider price;
    private javax.swing.JLabel principalImage;
    private javax.swing.JLabel rightImage;
    private javax.swing.JSlider slots;
    private javax.swing.JComboBox<SubType> subType;
    private javax.swing.JComboBox<WarriorType> type;
    private javax.swing.JComboBox<WeaponType> type1;
    private javax.swing.JTextField warriors;
    private javax.swing.JLabel weaponImage;
    // End of variables declaration//GEN-END:variables
}
